# Generated by Django 4.0 on 2022-01-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
    ]
