# Generated by Django 4.0 on 2022-01-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='project',
            new_name='project_id',
        ),
    ]
