# Generated by Django 4.0 on 2022-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_comment_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('back-end', 'back'), ('front-end', 'front'), ('ios', 'ios'), ('Android', 'android')], max_length=50),
        ),
    ]
